### ISSUE TITLE
Ajustar el api de custionario crud por modificaciones del modelo

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/cuestionario_crud#2]
Se debe Ajusta el api ya desarrollado por cambios por parte del DBA en la [Issue](https://github.com/udistrital/campus_cliente/issues/200), este modelo debe cumplir con los siguientes requerimientos:

- [x] Debe ser lo mas general posible para posible futuros cambios del sistema.
- [x] El modelo debe poder registrar todas las preguntas de la sección información familiar.
- [x] El modelo debe ser desarrollado en la herramienta pgmodeler.

Lider técnica: @mafeave

**Comment by fabianbarreto02** [comment]
Se Inicia proceso de ajuste del API

**Comment by fabianbarreto02** [comment]
Se espera revisión por parte  de la lider técnica : @mafeave

**Comment by mafeave** [comment]
Ajustar modelo de la documentación del Readme
